version: '3.8'

services:
  # ================= INFRA =================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    hostname: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    depends_on:
      - kafka
    networks:
      - app-network

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: livechat
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1q2w3e4r
      PGADMIN_CONFIG_SERVER_MODE: "False"
    depends_on:
      - postgres
    networks:
      - app-network

  # redis:
  #   image: redis:7-alpine
  #   container_name: redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app-network

  # ================= MICROSERVICES =================
  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: auth-service
    restart: unless-stopped
    environment:
      AUTH_GRPC_URL: "0.0.0.0:50051"
      DATABASE_URL: "postgresql://postgres:1q2w3e4r@postgres:5432/livechat"
      KAFKA_BROKER: "kafka:29092"
      REDIS_URL: "redis://host.docker.internal:6379"
    depends_on:
      - postgres
      - kafka
      # - redis
    networks:
      - app-network

  # chat-service:
  #   build:
  #     context: .
  #     dockerfile: apps/chat-service/Dockerfile
  #   container_name: chat-service
  #   restart: unless-stopped
  #   environment:
  #     CHAT_GRPC_URL: "0.0.0.0:50052"
  #     DATABASE_URL: "postgresql://postgres:1q2w3e4r@postgres:5432/livechat"
  #     KAFKA_BROKER: "kafka:29092"
  #     REDIS_URL: "redis://redis:6379"
  #   depends_on:
  #     - postgres
  #     - kafka
  #     - redis
  #   networks:
  #     - app-network

  # fanpage-service:
  #   build:
  #     context: .
  #     dockerfile: apps/fanpage-service/Dockerfile
  #   container_name: fanpage-service
  #   restart: unless-stopped
  #   environment:
  #     FANPAGE_GRPC_URL: "0.0.0.0:50053"
  #     DATABASE_URL: "postgresql://postgres:1q2w3e4r@postgres:5432/livechat"
  #     KAFKA_BROKER: "kafka:29092"
  #   depends_on:
  #     - postgres
  #     - kafka
  #   networks:
  #     - app-network

  # file-service:
  #   build:
  #     context: .
  #     dockerfile: apps/file-service/Dockerfile
  #   container_name: file-service
  #   restart: unless-stopped
  #   environment:
  #     FILE_GRPC_URL: "0.0.0.0:50054"
  #     DATABASE_URL: "postgresql://postgres:1q2w3e4r@postgres:5432/livechat"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network

  # ai-service:
  #   build:
  #     context: .
  #     dockerfile: apps/ai-service/Dockerfile
  #   container_name: ai-service
  #   restart: unless-stopped
  #   environment:
  #     AI_GRPC_URL: "0.0.0.0:50055"
  #     KAFKA_BROKER: "kafka:29092"
  #   depends_on:
  #     - kafka
  #   networks:
  #     - app-network

  # analytics-service:
  #   build:
  #     context: .
  #     dockerfile: apps/analytics-service/Dockerfile
  #   container_name: analytics-service
  #   restart: unless-stopped
  #   environment:
  #     ANALYTICS_GRPC_URL: "0.0.0.0:50056"
  #     DATABASE_URL: "postgresql://postgres:1q2w3e4r@postgres:5432/livechat"
  #     KAFKA_BROKER: "kafka:29092"
  #   depends_on:
  #     - postgres
  #     - kafka
  #   networks:
  #     - app-network

  # notification-service:
  #   build:
  #     context: .
  #     dockerfile: apps/notification-service/Dockerfile
  #   container_name: notification-service
  #   restart: unless-stopped
  #   environment:
  #     NOTIFICATION_GRPC_URL: "0.0.0.0:50057"
  #     KAFKA_BROKER: "kafka:29092"
  #     REDIS_URL: "redis://redis:6379"
  #   depends_on:
  #     - kafka
  #     - redis
  #   networks:
  #     - app-network

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    container_name: gateway
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      AUTH_GRPC_URL: "auth-service:50051"
      # CHAT_GRPC_URL: "chat-service:50052"
      # FANPAGE_GRPC_URL: "fanpage-service:50053"
      # FILE_GRPC_URL: "file-service:50054"
      # AI_GRPC_URL: "ai-service:50055"
      # ANALYTICS_GRPC_URL: "analytics-service:50056"
      # NOTIFICATION_GRPC_URL: "notification-service:50057"
    depends_on:
      - auth-service
      # - chat-service
      # - fanpage-service
      # - file-service
      # - ai-service
      # - analytics-service
      # - notification-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: