syntax = "proto3";

package auth;

service AuthService {
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc GetByIdUser(GetByIdUserRequest) returns (UserResponse);
    rpc Logout(GetByIdUserRequest) returns (LogoutResponse);
    rpc LoginV1(LoginV1Request) returns (LoginResponse);
}

message LogoutResponse {
  int32 code = 1;
  string message = 2;
}

message GetByIdUserRequest {
  int64 user_id = 1;
}

message UserResponse {
     int32 code = 1;
    string message = 2;
    User data = 3;
}

message LoginRequest {
    string email = 1;
    string password = 2;
}

message Role {
    int32 id = 1;
    string name = 2;
    int64 created_at = 3;
}

message User {
    int32 id = 1;
    string full_name = 2;
    string email = 3;
    string avatar = 4;
    bool is_online = 5;
    int64 created_at = 6;
    Role role = 7;
}

message LoginResponse {
    int32 code = 1;
    string message = 2;
    string access_token = 3;
    string refresh_token = 4;
    User user = 5;
    int64 startTime = 6;
    int64 endTime = 7;
}

message LoginV1Request {
    string email = 1;
    string full_name = 2;
    string avatar = 3;
    string provider = 4;
}