syntax = "proto3";

package FANPAGE_PACKAGE;

service FanPageService {
    rpc CreateConnectPageFacebook(CreateConnectRequest) returns (CreateConnectResponse);
    rpc TokenRenewal(TokenRenewalRequest) returns (TokenRenewalResponse);
    rpc GetPageId(GetPageIdRequest) returns (GetByIdResponse);
    rpc Syncing(SyncingRequest) returns (SyncingResponse);
    
}

message CreateConnectRequest {
    int64 user_id = 1;
    string access_token = 2;
}


message CreateConnectResponse {
    int32 code = 1;
    string message = 2;
}

message TokenRenewalRequest {
    int64 user_id = 1;
    int64 fanpage_id = 2;
    string access_token = 3;
}

message TokenRenewalResponse {
    int32 code = 1;
    string message = 2;
}

message GetPageIdRequest {
    int64 id = 1;
}

message GetByIdData {
   int32 id = 1;
   string page_id = 2;
   string page_name = 3;
   string page_avatar = 4;
   string syncStatus = 5;
}

message GetByIdResponse {
    int32 code = 1;
    string message = 2;
    GetByIdData data = 3;
}

message SyncingRequest {
    string page_id = 1;
}

message SyncingResponse {
    int32 code = 1;
    string message = 2;
    string data = 3;
}