syntax = "proto3";

package CHAT_PACKAGE;

service LabelService {
  rpc GetPaging(GetPagingLabelRequest) returns (LabelResponse);
  rpc Create(CreateLabelRequest) returns (LabelResponse);
  rpc Delete(DeleteLabelRequest) returns (LabelResponse);
  rpc Update(UpdateLabelRequest) returns (LabelResponse);
  rpc Restore(DeleteLabelRequest) returns (LabelResponse);
  rpc Copy(CopyLabelRequest) returns (LabelResponse);
  rpc DeleteAll(DeleteAllLabelRequest) returns (LabelResponse);
  
}

// ===== Request =====
message GetPagingLabelRequest {
  int32 pageIndex = 1;
  int32 limit = 2;
  string search = 3;
  string page_id = 4;
  bool is_deleted = 5;
}

message CreateLabelRequest {
  string name = 1;
  string color = 2;
  string page_id = 3;
  bool is_deleted = 4;
}

message DeleteLabelRequest {
  int64 id = 1;
  
}

message UpdateLabelRequest {
  string name = 1;
  string color = 2;
  string page_id = 3;
  bool is_deleted = 4;
   int64 id = 5;
}

message CopyLabelRequest {
   int64 source_id = 1;
  int64 landing_id = 2;
  string selectedKeys = 3;
  string mode = 4;
}

message DeleteAllLabelRequest {
  repeated int64 ids = 1;
}

// ===== Response chuẩn theo pattern code/message/data =====
message LabelResponse {
  int32 code = 1;
  string message = 2;
  string data = 3;
}

