syntax = "proto3";

package CHAT_PACKAGE;

service QuickReplyService {
  rpc Create(CreateQuickReplyRequest) returns (QuickReplyResponse);
  rpc GetPaging(GetPagingQuickReplyRequest) returns (QuickReplyResponse);
  
  
}

// ===== Request =====
message CreateQuickReplyRequest {
  string content = 1;
  int64 quick_reply_category_id = 2;
  string page_id = 3;
}

message GetPagingQuickReplyRequest {
  int32 pageIndex = 1;
  int32 limit = 2;
  string search = 3;
  string page_id = 4;
}

// ===== Response chuẩn theo pattern code/message/data =====
message QuickReplyResponse {
  int32 code = 1;
  string message = 2;
  string data = 3;
}

